version: '3.1'

services:

  db-postgres:
    image: postgres
    restart: always
    volumes:
      - ${DB_VOLUME}:/db
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      PGDATA: /db

  admin-container1:
    image: localhost/admin-container:v1
    restart: always
    ports: 
      - 3001:3000
    environment:
      ADMIN_LISTEN_HOST: :3000
      ADMIN_IP: admin-container2
      ADMIN_PORT: 3000
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      DB_ADDR: "db-postgres:5432"
      CONTAINER_NAME: admin-container1

  admin-container2:
    image: localhost/admin-container:v1
    restart: always
    entrypoint: ""
    command: sh -c "
     sleep 10 &&
     admin-go"
    ports: 
      - 3002:3000
    environment:
      ADMIN_LISTEN_HOST: :3000
      ADMIN_IP:  admin-container1
      ADMIN_PORT: 3000
      CONTAINER_NAME: admin-container2

# Adminer Only for test purpose
# TODO to be removed
  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080