version: '3.1'

services:

  db:
    image: postgres
    restart: always
    volumes:
      - ${DB_VOLUME}:/db
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      PGDATA: /db

# Adminer Only for test purpose
# TODO to be removed
  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080